title: Welcome to my Portfolio!
logo: "/Images/logo_Image.PNG?raw=true"
description: Here you'll find a number of my personal projects in various states of completion. <br> Feel free to have a look around. 
theme: jekyll-theme-dinky
