title: Welcome to my portfolio!
logo: "/Images/logo_Image.PNG?raw=true"
description: I'll be uploading my personal projects here along with my ideas and plans for updates i wish to make to these existing projects and any new project ideas i come up with.
theme: jekyll-theme-dinky
