title: Welcome to my portfolio website!
logo: "/Images/NicolaCrabtree_Photo.PNG?raw=true"
description: > #input text below
I'll be uploading my personal projects here along with my ideas and plans for updates i wish to make to these existing projects and any new project ideas i come up with.
<br><br>

theme: jekyll-theme-midnight
